# Generated by Django 4.2.2 on 2023-06-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_clientes_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
